export const catchphrasesSet = [
	'Ai',
	'Ai Ai Ai, AIII!',
	'Ai, gostei...',
	'Ai mamãe.. Ai meu Deus',
	'Aoooooooo, potência!',
	'CAVALO!',
	'CHEEEEEEGA!',
	'Dança gatinho, dança!',
	'Demaaaaaais',
	'É brincadeira em!',
	'Ele goooosta',
	'Irraaaaaaaaaa',
	'Calma meu filho, calma!',
	'Okay Okay',
	'PARE!',
	'Que papelão hein..',
	'TOME!',
	'UUUUUUUUUUUUI'
]
